"""
MoziToolKit Live Sync Module.
Provides real-time Minecraft WebSocket communication, VoxelStorage, Block Classification,
and Direct Mesh Generation.
"""

from .constants import (
    CONTRACT_VERSION,
    FACES,
    MTK_ANIM_ATLAS_HEIGHT,
    MTK_ANIM_ATLAS_WIDTH,
    MTK_ANIM_FRAME_HEIGHT,
    MTK_ANIM_FRAME_WIDTH,
    MTK_ANIM_TIMING,
    MTK_ATLAS_CHUNK_ID,
    MTK_ATLAS_HEIGHT,
    MTK_ATLAS_TEXTURE_ID,
    MTK_ATLAS_WIDTH,
    MTK_BIOME_TINT_COLOR,
    MTK_BIOME_TINT_DATA,
    MTK_BLOCK_X,
    MTK_BLOCK_Y,
    MTK_BLOCK_Z,
    MTK_FACE_DIR,
    MTK_EMISSIVE,
    MTK_IS_OPAQUE,
    MTK_MATERIAL_ID,
    MTK_TILE_SIZE,
    MTK_TILES_PER_ROW,
    MTK_UV_ROTATION,
    MTK_UV_TILING_TRANSFORM,
    UV_MAP,
    DEFAULT_WORLD_OBJECT_NAME,
    DEFAULT_WORLD_MESH_NAME,
)
from .classifier import (
    AIR_BLOCKS,
    BlockTypeEnum,
    CROSS_PLANTS,
    FLUID_BLOCKS,
    ParsedBlock,
    TRANSPARENT_BLOCKS,
    atlas_lookup_keys,
    classify_block_type_and_orientation,
    parse_and_classify,
)
from .client import SyncClientThread
from .material_manager import (
    LiveSyncMaterialManager,
    ResolvedFaceTexture,
)
from .mesh_builder import (
    WorldMeshBuildResult,
    CachedStateMeta,
    apply_block_delta_to_world,
    build_world_mesh,
    clear_mesh_builder_caches,
    get_cached_state_meta,
    get_shared_material_manager,
    preload_sync_world_data,
    sync_world_mesh,
    update_blocks_in_mesh,
)
from .storage import VoxelStorage, block_key, voxel_storage

__all__ = (
    "CONTRACT_VERSION",
    "FACES",
    "MTK_ANIM_ATLAS_HEIGHT",
    "MTK_ANIM_ATLAS_WIDTH",
    "MTK_ANIM_FRAME_HEIGHT",
    "MTK_ANIM_FRAME_WIDTH",
    "MTK_ANIM_TIMING",
    "MTK_ATLAS_CHUNK_ID",
    "MTK_ATLAS_HEIGHT",
    "MTK_ATLAS_TEXTURE_ID",
    "MTK_ATLAS_WIDTH",
    "MTK_BIOME_TINT_COLOR",
    "MTK_BIOME_TINT_DATA",
    "MTK_BLOCK_X",
    "MTK_BLOCK_Y",
    "MTK_BLOCK_Z",
    "MTK_FACE_DIR",
    "MTK_EMISSIVE",
    "MTK_IS_OPAQUE",
    "MTK_MATERIAL_ID",
    "MTK_TILE_SIZE",
    "MTK_TILES_PER_ROW",
    "MTK_UV_ROTATION",
    "MTK_UV_TILING_TRANSFORM",
    "UV_MAP",
    "DEFAULT_WORLD_OBJECT_NAME",
    "DEFAULT_WORLD_MESH_NAME",
    "AIR_BLOCKS",
    "BlockTypeEnum",
    "CROSS_PLANTS",
    "FLUID_BLOCKS",
    "ParsedBlock",
    "TRANSPARENT_BLOCKS",
    "atlas_lookup_keys",
    "classify_block_type_and_orientation",
    "parse_and_classify",
    "SyncClientThread",
    "LiveSyncMaterialManager",
    "ResolvedFaceTexture",
    "WorldMeshBuildResult",
    "apply_block_delta_to_world",
    "build_world_mesh",
    "clear_mesh_builder_caches",
    "get_shared_material_manager",
    "preload_sync_world_data",
    "sync_world_mesh",
    "update_blocks_in_mesh",
    "VoxelStorage",
    "block_key",
    "voxel_storage",
)
