"""
MoziToolKit Live Sync Module.
Provides real-time Minecraft WebSocket communication, VoxelStorage, Block Classification,
and Procedural Point Cloud Generation.
"""

from .constants import (
    BLOCK_CENTER,
    BLOCK_KEY,
    BLOCK_STATE,
    BLOCK_TYPE,
    CONTRACT_VERSION,
    DIRECTIONAL_FACE_V_FLIP,
    FACES,
    INSTANCE_ROTATION,
    MC_POSITION,
    MTK_ANIM_ATLAS_HEIGHT,
    MTK_ANIM_ATLAS_WIDTH,
    MTK_ANIM_FRAME_HEIGHT,
    MTK_ANIM_FRAME_WIDTH,
    MTK_ANIM_TIMING,
    MTK_ATLAS_CHUNK_ID,
    MTK_ATLAS_HEIGHT,
    MTK_ATLAS_TEXTURE_ID,
    MTK_ATLAS_WIDTH,
    MTK_BIOME_TINT_COLOR,
    MTK_BIOME_TINT_DATA,
    MTK_EMISSIVE,
    MTK_IS_OPAQUE,
    MTK_MATERIAL_ID,
    MTK_TILE_SIZE,
    MTK_TILES_PER_ROW,
    MTK_UV_ROTATION,
    MTK_UV_TILING_TRANSFORM,
    TEMPLATE_INDEX,
    clear_point_attributes,
    face_attribute,
)
from .classifier import (
    AIR_BLOCKS,
    BlockTypeEnum,
    CROSS_PLANTS,
    FLUID_BLOCKS,
    ParsedBlock,
    TRANSPARENT_BLOCKS,
    atlas_lookup_keys,
    classify_block_type_and_orientation,
    parse_and_classify,
)
from .client import SyncClientThread
from .point_cloud import (
    PointCloudBuildResult,
    set_baker_resource_source,
    update_world_point_cloud,
)
from .storage import VoxelStorage, block_key, voxel_storage
from .template_catalog import (
    TEMPLATE_COLLECTION_NAME,
    TemplateCatalog,
    get_or_create_template_collection,
    get_template_index_map,
    template_catalog,
)

__all__ = (
    "BLOCK_CENTER",
    "BLOCK_KEY",
    "BLOCK_STATE",
    "BLOCK_TYPE",
    "CONTRACT_VERSION",
    "DIRECTIONAL_FACE_V_FLIP",
    "FACES",
    "INSTANCE_ROTATION",
    "MC_POSITION",
    "MTK_ANIM_ATLAS_HEIGHT",
    "MTK_ANIM_ATLAS_WIDTH",
    "MTK_ANIM_FRAME_HEIGHT",
    "MTK_ANIM_FRAME_WIDTH",
    "MTK_ANIM_TIMING",
    "MTK_ATLAS_CHUNK_ID",
    "MTK_ATLAS_HEIGHT",
    "MTK_ATLAS_TEXTURE_ID",
    "MTK_ATLAS_WIDTH",
    "MTK_BIOME_TINT_COLOR",
    "MTK_BIOME_TINT_DATA",
    "MTK_EMISSIVE",
    "MTK_IS_OPAQUE",
    "MTK_MATERIAL_ID",
    "MTK_TILE_SIZE",
    "MTK_TILES_PER_ROW",
    "MTK_UV_ROTATION",
    "MTK_UV_TILING_TRANSFORM",
    "TEMPLATE_INDEX",
    "clear_point_attributes",
    "face_attribute",
    "AIR_BLOCKS",
    "BlockTypeEnum",
    "CROSS_PLANTS",
    "FLUID_BLOCKS",
    "ParsedBlock",
    "TRANSPARENT_BLOCKS",
    "atlas_lookup_keys",
    "classify_block_type_and_orientation",
    "parse_and_classify",
    "SyncClientThread",
    "PointCloudBuildResult",
    "set_baker_resource_source",
    "update_world_point_cloud",
    "VoxelStorage",
    "block_key",
    "voxel_storage",
    "TEMPLATE_COLLECTION_NAME",
    "TemplateCatalog",
    "template_catalog",
    "get_or_create_template_collection",
    "get_template_index_map",
)
