"""
Materials, resource pack indexing, and texture atlas management subpackage.
Organized into focused subpackages:
- pack: Resource Pack extraction, stacking, caching, and animation timing
- atlas: Texture Atlas bin packing, layout math, generation, and chunk builder
- standalone: Standalone per-texture material generator and channel aligner
- biome: Biome palettes, hardcoded tints, and color space conversion
- nodes: Shader node tree building, PBR channel wiring, and interpolation
- matching: Importer format adapters and texture identification
- pipeline: Mesh face provenance, attributes, and UV pipelines
- yefira: Procedural point-cloud world integration and Geometry Nodes binding
"""

from .constants import (
    DEFAULT_NAMESPACE,
    PROP_PACK_HASH,
    PROP_PACK_HASH_SHORT,
    PROP_SOURCE_NAMESPACE,
    PROP_SOURCE_TEXTURE,
    PROP_SOURCE_FILE,
    PROP_MATERIAL_ID,
    PROP_ATLAS_CHUNK_ID,
    PROP_ATLAS_CHUNK_KIND,
    PROP_ATLAS_CHUNK_CATEGORY,
    PROP_ATLAS_MAPPING,
    PROP_ATLAS_WIDTH,
    PROP_ATLAS_HEIGHT,
    PROP_TILE_SIZE,
    PROP_TILES_PER_ROW,
    PROP_CREATED_BY,
    PROP_PROVENANCE_SCHEMA_VERSION,
    ATLAS_CATEGORY_BLOCKS,
    ATLAS_CATEGORY_ITEMS,
    ATLAS_CATEGORY_PARTICLES,
    ATLAS_CATEGORY_PAINTINGS,
    ATLAS_CATEGORY_ARMOR_TRIMS,
    ATLAS_CATEGORY_CHEST,
    ATLAS_CATEGORY_SHULKER_BOXES,
    ATLAS_CATEGORY_SHIELD_PATTERNS,
    ATLAS_CATEGORY_BANNER_PATTERNS,
    ATLAS_CATEGORY_DECORATED_POT,
    ATLAS_CATEGORY_CELESTIALS,
    ATLAS_CATEGORY_GUI,
    ATLAS_CATEGORY_MAP_DECORATIONS,
    ATLAS_CATEGORY_ENTITIES,
    ATLAS_CATEGORY_MISC,
    ATLAS_CATEGORY_PRIORITY,
    RECT_PACKED_CATEGORIES,
    classify_texture_category,
    ATTR_ATLAS_CHUNK_ID,
    ATTR_ATLAS_TEXTURE_ID,
    ATTR_FACE_MATERIAL_ID,
    ATTR_IS_OPAQUE,
    ATTR_ALPHA_MODE,
    ATTR_SOURCE_TEXTURE_KEY,
    ATTR_SOURCE_ORIGIN,
    ATTR_UV_ROTATION,
    ATTR_UV_TILING_SCALE,
    ATTR_UV_TILING_LOCATION,
    ATTR_UV_TILING_TRANSFORM,
    ATTR_BIOME_TINT_DATA,
    ATTR_BIOME_TINT_COLOR,
    ATTR_ANIM_TIMING,
    ATTR_ANIM_FRAME_SIZE,
    ATTR_TINT_WEIGHT,
    ATTR_BASE_TINT_WEIGHT,
    ATTR_OVERLAY_TINT_WEIGHT,
    ATTR_TINT_COLOR,
    ATTR_TINT_TYPE,
    ATTR_HARDCODED_COLOR,
    ATTR_USE_HARDCODED,
    ATTR_BIOME_TEMPERATURE,
    ATTR_BIOME_HUMIDITY,
    PROP_HAS_OVERLAY,
    PROP_OVERLAY_TEXTURE,
    PROP_TINT_CATEGORY,
    PROVENANCE_SCHEMA_VERSION,
    FACE_ORDER,
    ATLAS_FORMAT_VERSION,
    ANIM_AND_ATLAS_ATTR_NAMES,
    LEGACY_SPLIT_ATTR_NAMES,
    BLOCK_TO_TEXTURE_ALIASES,
)

from .biome import (
    hex_to_rgb,
    srgb_to_linear,
    hex_to_linear_rgb,
    hex_to_rgba,
    hex_to_linear_rgba,
    linear_to_srgb,
    linear_rgba_to_hex,
    BIOME_PALETTES,
    HARDCODED_BLOCK_TINTS,
    KNOWN_OVERLAY_PAIRS,
    TINT_TYPE_NONE,
    TINT_TYPE_GRASS,
    TINT_TYPE_FOLIAGE,
    TINT_TYPE_WATER,
    TINT_TYPE_HARDCODED,
    BiomeResolver,
    get_biome_colors,
    classify_tint_category,
)

from .pack import (
    ZipResourcePack,
    get_cache_dir,
    get_temp_extraction_dir,
    clean_obsolete_stack_caches,
    get_cache_stats,
    clear_resource_pack_cache,
    get_pack_hash,
    get_directory_hash,
    parse_mcmeta,
    derive_texture_name,
    texture_category_priority,
    ResourcePackStack,
    get_configured_pack_stack,
    get_pack_stack_fingerprint,
    get_material_animation_info,
    get_texture_info_animation_info,
)

from .atlas import (
    PackedRect,
    MaxRectsBinPack,
    pack_category_textures,
    face_index_from_normal,
    static_cell,
    chunk_cell,
    atlas_uv_from_local,
    atlas_uv_from_rect,
    local_uv_from_atlas,
    local_uv_from_rect,
    find_texture_id_from_atlas_uv,
    remap_uv_to_local,
    remap_local_to_target_uv,
    remap_uv_coordinate,
    AtlasGenerator,
    build_atlas_material,
    build_atlas_chunk_materials,
    AtlasReplacementEngine,
)

from .standalone import (
    StandaloneGenerator,
    STANDALONE_FORMAT_VERSION,
    align_standalone_textures,
    is_channel_animated,
    StandaloneReplacementEngine,
)

from .nodes import (
    load_image_texture,
    set_material_displacement_method,
    build_channel_nodes,
    rebuild_material,
    inspect_material_nodes,
    repair_material_nodes,
    set_materials_texture_interpolation_closest,
    process_node_tree_interpolation,
)

from .matching import (
    ImporterAdapter,
    MaterialMatchPreset,
    ICE_CUBE_ADAPTER,
    JMC2OBJ_ADAPTER,
    MINEWAYS_ADAPTER,
    GENERIC_ADAPTER,
    ADAPTERS,
    ICE_CUBE_PRESET,
    JMC2OBJ_PRESET,
    MINEWAYS_PRESET,
    GENERIC_PRESET,
    MATCH_PRESETS,
    get_importer_adapter,
    get_material_match_preset,
    material_source_origin,
    extract_material_texture_keys,
    extract_face_texture_info,
    is_ice_cube_material,
    is_ice_cube_internal_face_material,
    ice_cube_texture_candidates,
    ice_cube_name_aliases,
    ice_cube_legacy_aliases,
    is_jmc2obj_material,
    jmc2obj_texture_candidates,
    is_mineways_material,
    mineways_texture_candidates,
    generic_texture_candidates,
    base_texture_candidates,
    normalized_image_key,
    extract_texture_provenance_from_image,
    ICE_CUBE_STATIC_ASSET_UUID_ALIASES,
    MINEWAYS_TILES_TABLE,
    is_mineways_atlas_image,
    find_mineways_atlas_image,
    is_mineways_atlas_material,
    decode_mineways_face_uv,
    remap_mineways_atlas_uv_to_local,
    find_albedo_image_from_material,
    find_face_image,
    get_material_pixel_step,
)

from .pipeline import (
    without_blender_suffix,
    canonical_texture_key,
    split_texture_key,
    detect_material_mode,
    is_mozi_material,
    get_face_source_origin,
    get_face_source_texture_key,
    get_atlas_mapping_from_material,
    get_material_atlas_dimensions,
    get_atlas_mapping_from_mesh,
    write_provenance_schema,
    write_face_source_provenance,
    ensure_face_attribute,
    read_face_vector_attribute,
    read_face_float_attribute,
    read_face_string_attribute,
    read_face_tiling,
    compute_biome_tint_attributes,
    apply_biome_tint_attributes,
    cleanup_legacy_mesh_attributes,
    cleanup_object_anim_properties,
    remap_polygon_loop_uvs,
    remap_face_uv_to_local,
    restore_face_atlas_tiling,
    straighten_and_normalize_face_uv,
    name_replaced_material,
    find_existing_replacement,
    apply_mesh_face_materials_and_provenance,
    build_material_face_cache,
    cached_face_texture_info,
    get_polygon_material_indices,
    apply_generic_procedural_atlas_material,
)

from .yefira import (
    is_yefira_object,
    has_yefira_objects,
    write_yefira_point_atlas_attributes,
    setup_yefira_point_cloud_attributes,
    notify_yefira_update,
    apply_yefira_atlas_materials,
    extract_atlas_parameters,
    find_bound_atlas_material,
    find_all_atlas_chunk_materials,
    get_or_create_atlas_material,
    setup_material_slots_for_object,
    find_active_atlas_material,
    parse_atlas_mapping,
    build_block_face_lut,
    build_block_face_atlas_ids,
    build_block_face_tint_lut,
    build_block_face_anim_lut,
    build_block_face_uv_rot_lut,
    build_block_face_uv_bounds_lut,
    resolve_block_state_face_locations,
    refresh_baker_sources,
)
