"""Live Sync Meshing Subsystem."""

from .cache import (
    COMMON_PREWARM_STATES,
    CachedStateMeta,
    _GLOBAL_STATE_META_CACHE,
    clear_mesh_builder_caches,
    get_cached_state_meta,
    preload_sync_world_data,
)
from .fluid import (
    generate_fluid_buffer_faces,
    generate_fluid_mesh_faces,
    get_fluid_base_height,
    is_fluid_block,
)
from .geometry import (
    CUBE_FACE_CANONICAL_UVS,
    CUBE_FACE_MC_VERTICES,
    DIR_TO_INDEX,
    MC_DIR_OFFSETS,
    RawSectionGeometryBuffer,
    generate_section_geometry_buffer,
    generate_single_block_faces,
    generate_voxel_geometry,
    mc_local_to_blender,
)
from .hierarchy import (
    _get_mesh_vertex_and_face_count,
    _safe_remove_section_object,
    clear_all_section_objects,
    find_root_section_children,
    get_or_create_world_root,
    get_section_mesh_name,
    get_section_object_name,
    is_yefira_child_section,
    is_yefira_object,
    is_yefira_root_object,
    prune_out_of_bounds_section_objects,
    resolve_world_root_object,
    sync_child_section_names,
)
from .world_mesh import (
    WorldMeshBuildResult,
    apply_block_delta_to_world,
    apply_geometry_buffer_to_mesh,
    build_single_section_mesh,
    build_world_mesh,
    sync_world_mesh,
    update_blocks_in_mesh,
)

__all__ = (
    "CachedStateMeta",
    "COMMON_PREWARM_STATES",
    "_GLOBAL_STATE_META_CACHE",
    "clear_mesh_builder_caches",
    "get_cached_state_meta",
    "preload_sync_world_data",
    "generate_fluid_buffer_faces",
    "generate_fluid_mesh_faces",
    "get_fluid_base_height",
    "is_fluid_block",
    "CUBE_FACE_CANONICAL_UVS",
    "CUBE_FACE_MC_VERTICES",
    "DIR_TO_INDEX",
    "MC_DIR_OFFSETS",
    "RawSectionGeometryBuffer",
    "generate_section_geometry_buffer",
    "generate_single_block_faces",
    "generate_voxel_geometry",
    "mc_local_to_blender",
    "_get_mesh_vertex_and_face_count",
    "_safe_remove_section_object",
    "clear_all_section_objects",
    "find_root_section_children",
    "get_or_create_world_root",
    "get_section_mesh_name",
    "get_section_object_name",
    "is_yefira_child_section",
    "is_yefira_object",
    "is_yefira_root_object",
    "prune_out_of_bounds_section_objects",
    "resolve_world_root_object",
    "sync_child_section_names",
    "WorldMeshBuildResult",
    "apply_block_delta_to_world",
    "apply_geometry_buffer_to_mesh",
    "build_single_section_mesh",
    "build_world_mesh",
    "sync_world_mesh",
    "update_blocks_in_mesh",
)
